LES015E
302
                  1        1 FCC      20 QD80290                         
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                           5               108834185
                           6             20 CAS, 1 TO 20
                           7             FORMED PER ED5D872-30 G5
                           8             CA DES    X-DIM
                           9             1  CM60A  20-0
                          10             2  CM60B  20-0
                          11             3  CM60C  20-0
                          12             4  CM60D  20-0
                          13             5  CM60A  20-0
                          14             6  CM60B  20-0
                          15             7  CM60C  20-0
                          16             8  CM60D  20-0
                          17             9  CM60A  20-0
                          18             10 CM60B  20-0
                          19             11 CM60C  20-0
                          20             12 CM60D  20-0
                          21             13 CM60A  20-0
                          22             14 CM60B  20-0
                          23             15 CM60C  20-0
                          24             16 CM60D  20-0
                          25             17 CM60A  20-0
                          26             18 CM60B  20-0
                          27             19 CM60C  20-0
                          28             20 CM60D  20-0
                  2        1 FCC       1 ED5D865-11-G1B                  14 
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                  2   A    1          80 105419519         FT 
                           2               816AS
                           3             4 CAS, 21 TO 24
                           4             FORMED PER ED5D865-30 G1B
                           5             FORMED PER ED5D865-30 G3B
                           6             FORMED PER ED5D865-30 G2B
                           7             FORMED PER ED5D865-30 G4B
                           8             CA DES  TO EQL&TERM  X-DIM
                           9             21 KA1  028-075-151  20-0
                          10             22 KA2  028-075-119  20-0
                          11             23 KA3  053-075-151  20-0
                          12             24 KA4  053-075-119  20-0
                  3        1 FCC       1 ED5D865-11-G2                   14 
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                  3   A    1          80 104309208         FT 
                           2               104309208
                           3             4 CAS, 25 TO 28
                           4             FORMED PER ED5D865-30 G5
                           5             FORMED PER ED5D865-30 G7
                           6             FORMED PER ED5D865-30 G6
                           7             FORMED PER ED5D865-30 G8
                           8             CA DES  TO EQL&TERM  X-DIM
                           9             25 KA5  019-110-541  20-0
                          10             26 KA6  045-110-154  20-0
                          11             27 KA7  019-110-741  20-0
                          12             28 KA8  045-110-341  20-0
                  4        1 FCC       2 ED5D865-11-G5                   14 
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                  4   A    1         480 106007743         FT 
                           2               735A
                           3             4 CAS, 29 TO 32
                           4             FORMED PER ED5D865-30 G13
                           5             FORMED PER ED5D865-30 G14
                           6             CA DES   FROM EQL/TERM  X-DIM
                           7             29 KA13  024-309-079    120-0
                           8             30 KA14  024-309-079    120-0
                           9             31 KA13  024-309-073    120-0
                          10             32 KA14  024-309-073    120-0
                  5        1 FCC       2 ED5D865-11-G7                   14 
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                  5   A    1         480 106007743         FT 
                           2               735A
                           3             4 CAS, 33 TO 36
                           4             FORMED PER ED5D865-30 G17
                           5             FORMED PER ED5D865-30 G18
                           6             CA DES   FROM EQL/TERM  X-DIM
                           7             33 KA17  024-309-097    120-0
                           8             34 KA18  024-309-097    120-0
                           9             35 KA17  024-329-097    120-0
                          10             36 KA18  024-329-097    120-0
                  6        1 FCC       2 ED5D865-11-G9A                  14 
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                  6   A    1          80 105310650         FT 
                           2               1249004A
                           3             4 CAS, 37 TO 40
                           4             FORMED PER ED5D865-30 G21A
                           5             FORMED PER ED5D865-30 G22A
                           6             CA DES   FROM  TO FR
                           7             37 KA21  CM3   SM001 SMC000
                           8             38 KA22  CM3   SM001 SMC000
                           9             39 KA21  CM3   SM001 SMC000
                          10             40 KA22  CM3   SM001 SMC000
                          11             CA FROM EQL/TERM TO EQL/TERM
                          12             37 024-309-079   00062-014-300
                          13             38 024-309-079   00062-014-100
                          14             39 024-309-073   00062-022-300
                          15             40 024-309-073   00062-022-100
                          16             CA X-DIM
                          17             37 20-0
                          18             38 20-0
                          19             39 20-0
                          20             40 20-0
                  7        1 FCC       1 ED5D500-21-G35CE                146
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                  7   A    1         100 105412605         FT 
                           2               822A
                           3             2 CAS, 41 TO 42
                           4             FORMED PER ED5D505-30 G73A,89A
                  7   B    1         100 105412530         FT 
                           2               812A
                           3             2 CAS, 43 TO 44
                           4             FORMED PER ED5D505-30 G211,212
                           5             CA DES    FROM FR  TO FR
                           6             41 JV73A  M 00  D0 CSPC D0
                           7             42 JV89A  M 00  D0 CSPC D0
                           8             43 JV211  M 00  D0 CSPC D0
                           9             44 JV212  M 00  D0 CSPC D0
                          10             CA TO EQL&TERM X-DIM
                          11             41 019-102-135 50-0
                          12             42 045-102-135 50-0
                          13             43 028-060-319 50-0
                          14             44 053-060-319 50-0
                  8        1 FCC       1 ED5D500-21-G35CG                146
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                  8   A    1         100 105412563         FT 
                           2               816A
                           3             2 CAS, 45 TO 46
                           4             FORMED PER ED5D505-30 G105B
                           5             FORMED PER ED5D505-30 G109B
                           6             CA DES     X-DIM
                           7             45 JV105B  50-0
                           8             46 JV109B  50-0
                  9        1 FCC       1 ED5D500-21-G36                  146
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                  9   A    1          50 105412522         FT 
                           2               811A
                           3             1 CA, 47
                           4             FORMED PER ED5D505-30 G13
                           5             CA DES   X-DIM
                           6             47 JV13  50-0
                 10        1 FCC       1 ED5D500-21-G194B                146
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                 10   A    1          50 408140499         FT 
                           2               KS13385 L1
                           3             1 CA, 48
                           4             FORMED PER ED5D586-30 G6A
                           5             CA DES   X-DIM
                           6             48 JF6A  50-0
                 11        1 FCC       1 ED5D505-30-G15                  55 
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                 11   A    1          50 105412910         FT 
                           2               285A
                           3             1 CA, 49
                           4             CA DES   X-DIM
                           5             49 JV15  50-0
                 12        1 FCC       6 ED5D500-21-G63A                 146
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                 12   A    1         300 105419477         FT 
                           2               812AS
                           3             6 CAS, 50 TO 55
                           4             FORMED PER ED3T076-20 G58
                           5             CA DES   FROM FR TO FR
                           6             50 0200  CSPC D0 STLWS D0
                           7             51 0201  CSPC D0 STLWS D0
                           8             52 0210  CSPC D0 STLWS D0
                           9             53 0211  CSPC D0 STLWS D0
                          10             54 1210  CSPC D0 STLWS D0
                          11             55 1211  CSPC D0 STLWS D0
                          12             CA FROM EQL/TERM X-DIM
                          13             50 028-094-132   50-0
                          14             51 028-094-332   50-0
                          15             52 028-102-132   50-0
                          16             53 028-102-332   50-0
                          17             54 053-102-132   50-0
                          18             55 053-102-332   50-0
                 13        1 FCC       2 ED5D500-21-G72C                 146
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                 13   A    1         100 105419469         FT 
                           2               811AS
                           3             2 CAS, 56 TO 57
                           4             FORMED PER ED3T076-20 G62
                           5             CA DES   FROM FR TO FR
                           6             56 1200  CSPC D0 3500
                           7             57 1201  CSPC D0 3500
                           8             CA FROM EQLTERM1 FROM EQLTERM2
                           9             56 053-094-132   053-094-145
                          10             57 053-094-332   053-094-345
                          11             CA X-DIM
                          12             56 50-0
                          13             57 50-0
                 14        1 FCC       2 ED5D500-21-G467                 146
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                 14   A    1         100 105412530         FT 
                           2               812A
                           3             2 CAS, 58 TO 59
                           4             FORMED PER ED3T076-20 G70
                           5             CA DES   FROM FR
                           6             58 1101  CSPC D0
                           7             59 1102  CSPC D0
                           8             CA TO FR
                           9             58 M 00 SPLITTER
                          10             59 M 00 SPLITTER
                          11             CA FROM EQL/TERM X-DIM
                          12             58 045-186-132   50-0
                          13             59 045-186-332   50-0
                 15        1 FCC       6 ED5D500-21-G466                 146
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                 15   A    1         300 105412530         FT 
                           2               812A
                           3             6 CAS, 60 TO 65
                           4             FORMED PER ED3T076-20 G69
                           5             CA DES   FROM FR
                           6             60 0220  CSPC D0
                           7             61 0221  CSPC D0
                           8             62 0222  CSPC D0
                           9             63 1220  CSPC D0
                          10             64 1221  CSPC D0
                          11             65 1222  CSPC D0
                          12             CA TO FR
                          13             60 M 00 NTS
                          14             61 M 00 NTS
                          15             62 M 00 NTS
                          16             63 M 00 NTS
                          17             64 M 00 NTS
                          18             65 M 00 NTS
                          19             CA FROM EQL/TERM X-DIM
                          20             60 028-110-132   50-0
                          21             61 028-110-332   50-0
                          22             62 028-110-532   50-0
                          23             63 053-110-132   50-0
                          24             64 053-110-332   50-0
                          25             65 053-110-532   50-0
                 16        1 FCC       1 ED5D824-11-G22                  18 
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                 16   A    1          12 108834185         FT 
                           2               108834185
                           3             1 CA, 66
                           4             FORMED PER ED5D824-30 G3
                           5             CA DES    FROM      TO        X-DIM
                           6             66 PA110  00037-004 00015-016 12-0
                 17        1 FCC       1 ED5D872-11-G21B                 37 
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                 17   A    1          24 108834136         FT 
                           2               108834136
                           3             2 CAS, 67 TO 68
                           4             FORMED PER ED5D872-30 G2A
                           5             CA DES     FR EQL1   FR EQL2
                           6             67 LA700B  00037-003 R
                           7             68 LA700C  00037-004 R
                           8             CA X-DIM
                           9             67 12-0
                          10             68 12-0
                 18        1 FCC       4 ED5D500-21-G148C                146
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                 18   A    1        1920 106007743         FT 
                           2               735A
                           3             16 CAS, 69 TO 84
                           4             FORMED PER ED5D503-32 G350C
                           5             FORMED PER ED5D503-32 G351C
                           6             CA       DES     FR
                           7             69 TO 70 JR350C  SM001 SMC000
                           8             71 TO 72 JR351C  SM001 SMC000
                           9             73 TO 74 JR350C  SM001 SMC000
                          10             75 TO 76 JR351C  SM001 SMC000
                          11             77 TO 78 JR350C  SM001 SMC000
                          12             79 TO 80 JR351C  SM001 SMC000
                          13             81 TO 82 JR350C  SM001 SMC000
                          14             83 TO 84 JR351C  SM001 SMC000
                          15             CA       FROM EQL/TERM  X-DIM
                          16             69 TO 70 00062-014-340  120-0
                          17             71 TO 72 00062-014-140  120-0
                          18             73 TO 74 00062-022-340  120-0
                          19             75 TO 76 00062-022-140  120-0
                          20             77 TO 78 00062-030-340  120-0
                          21             79 TO 80 00062-030-140  120-0
                          22             81 TO 82 00062-038-340  120-0
                          23             83 TO 84 00062-038-140  120-0
                 19        1 FCC       7 ED5D621-23-G13                  7  
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             7 CAS, 85 TO 91
                           5             FORMED PER ED5D621-24 G55
                           6             CA DES     FR
                           7             85 SIPT-1  SM001 SMC000
                           8             86 SIPT-1  SM001 SMC000
                           9             87 SIPT-1  SM001 SMC000
                          10             88 SIPT-1  SM001 SMC000
                          11             89 SIPT-1  SM001 SMC000
                          12             90 SIPT-1  SM001 SMC000
                          13             91 SIPT-1  SM001 SMC000
                          14             CA FROM EQL&TERM  X-DIM
                          15             85 00053-006      12-0
                          16             86 00053-022      12-0
                          17             87 00053-030      12-0
                          18             88 00053-054      12-0
                          19             89 00053-136      12-0
                          20             90 00053-160      12-0
                          21             91 00053-168      12-0
                 20        1 FCC       7 ED5D621-23-G12                  7  
                           2 SCE         QD/QD/X
                           3             CONN CA ASSY
                           4             F/E
                 20   A    1         700 408872968         FT 
                           2               1624P
                           3             7 CAS, 92 TO 98
                           4             FORMED PER ED5D621-24 G51
                           5             CA DES     FR
                           6             92 SIPT-2  SM001 SMC000
                           7             93 SIPT-2  SM001 SMC000
                           8             94 SIPT-2  SM001 SMC000
                           9             95 SIPT-2  SM001 SMC000
                          10             96 SIPT-2  SM001 SMC000
                          11             97 SIPT-2  SM001 SMC000
                          12             98 SIPT-2  SM001 SMC000
                          13             CA FROM EQL&TERM  X-DIM
                          14             92 00068-032      100-0
                          15             93 00068-032      100-0
                          16             94 00068-032      100-0
                          17             95 00068-032      100-0
                          18             96 00068-032      100-0
                          19             97 00068-032      100-0
                          20             98 00068-032      100-0
