LES015E
361
0                 1        1           1 J5D020C-1-L1                     27
                           2 SCE         QD/QD/X
                           3             COMMUNICATION MODULE 3 CABINET
                           4 C           CM3 00
                           5 SP          CONTROL GROUP D0
                           6             E/W
                  1   A    1           1 J5D020C-1-L2B                   
                           2             EQL 011F
                           3             EQL 011R
                  1   B    1           1 J5D020C-1-L4A                   
                           2             EQL 069
                  1   C    1           2 J5D020C-1-L6                    
                           2             EQL 024F
                           3             EQL 024R
                  1   D    1           2 J5D020C-1-L10B                  
                  1   E    1           2 J5D020C-1-L11B                  
                  1   F    1           4 J5D020C-1-L12                   
                  1   G    1           2 J5D020C-1-L13A                  
                  1   H    1          10 J5D020C-1-L16                   
                           2             024F/R-093-019,
                           3             024F/R-133-019,
                           4             024F/R-173-019,
                           5             024F/R-213-019,
0                          6             024F/R-253-019
                  1   J    1           1 J5D020C-1-LA                    
                  1   K    1           2 J5D020C-1-LB                    
                  1   L    1           1 J5D020C-1-LC                    
                  1   M    1           1 J5D020C-1-LF1                   
                  1   N    1           1 J5D020C-1-LG1                   
                  1   P    1           1 J5D020C-1-LG2                   
                  1   Q    1           1 J5D020C-1-LG3                   
                  1   R    1           1 J5D020C-1-LG9                   
                  1   S    1           1 ED5D695-16-G1                    11
                           2             BLANK LABEL FOR CAB ADDR -(CM3)-
                  1   T    1           1 ED5D865-10-G1                     9
                           2             POWER AND ALARM CABLE FOR CMU2
                  1   U    1           1 ED5D865-10-G3B                    9
                           2             CSI JUMPER CABLE FOR CMU2
                           3             (FRT & REAR) BASE CABINET ONLY.
                  1   V    1           1 ED5D865-10-G3C                    9
                           2             X-COUPLED CABLE FOR CMU2
                  1   W    1           1 ED5D865-10-G5                     9
                           2             ADDRS. JUMPERS FOR 3B21D CH12/CH14
                  1   X    1           1 ED5D865-10-G9                     9
                           2             F/F ALM IND. STRIP & FAN PWR CABLE
                  1   Y    1           1 ED5D785-70-G2B                   24
                           2             DOOR ASSY KIT -  EMC (CM3)-
                  1  AA    1           2 ED5D785-70-G3B                   24
                           2             F/F ALM IND STRIP -  EMC (CM3)-
                  1  AB    1           1 ED5D785-70-G4B                   24
                           2             EMC FRAME ADDITION KIT
0                 2        1 53C       1 J5D003N-2-L1                      9
                           2 SCE         QD/QD/X
                           3             5ESS-2000 CABINET
                           4 C           SM 001 SMC 000
                           5             FID LABEL -SMC0050-
                           6             SP CONTROL GROUP D0
                           7 FID         1,01,SMC00,50,0
                           8             E/W
                  2   A    1           1 J5D003N-2-L7                    
                  2   B    1           1 J5D003N-2-L8                    
                  2   C    1           1 J5D003N-2-L9                    
                  2   D    1           1 J5D003N-2-L10                   
                  2   E    1           1 J5D003N-2-L11                   
                  2   F    1           1 J5D003N-2-LC                    
                  2   G    1           1 J5D003N-2-LF2                   
                  2   H    1           1 J5D003N-2-LG                    
                  2   J    1           1 J5D073AA-1-L1                    23
                           2             INTELLIGENT PACKET SWITCH
                           3 C           SM 001 SMC 000/IPS 00/EQL F00037
                           4             FUSE POS 032A,032B,032C
                           5             FUSE POS 141A,141B,141C
                           6             E/W
                  2   K    1           2 J5D073AA-1-L2B                  
0                 2   L    1           2 J5D073AA-1-L3B                  
                  2   M    1           1 J5D073AA-1-L5B                  
                           2 C           SM 001 SMC 000/IPS 00/EQL
                           3 #           00037-004
                  2   N    1           1 J5D073AA-1-L100                 
                  2   P    1           2 J5D073AA-1-L105                 
                  2   Q    1          13 J5D073AA-1-LB1                  
                  2   R    1           1 J5D073AA-1-LD3                  
                  2   S    1           1 J5D073AA-1-LF1                  
                  2   T    1           1 J5D073AA-1-LG1                  
                  2   U    1           1 J5D073AA-1-LK1                  
                  2   V    1           1 J5D073AA-1-LK3                  
                  2   W    1           1 J5D073AA-1-L1                    23
                           2             INTELLIGENT PACKET SWITCH
                           3 C           SM 001 SMC 000/iOIU 00/EQL R00037
                           4             FUSE POS 041A,041B
                           5             FUSE POS 150B,150C
                           6             E/W
                  2   X    1           4 J5D073AA-1-L50                  
                           2 C           SM 001 SMC 000/IPS 00
                           3             SHOP INFORMATION
                           4             VEQL  SLOT    OIU CONNECTED TO
                           5 SP          37R   003,004  00   SM 001
                           6 SP          37R   005,006  00   SM 001
                  2   Y    1           4 J5D073AA-1-L51                  
                  2  AA    1           2 J5D073AA-1-L105                 
                  2  AB    1          14 J5D073AA-1-LB1                  
                  2  AC    1           1 J5D073AA-1-LE3                  
                  2  AD    1           1 J5D073AA-1-LF2                  
                  2  AE    1           1 J5D073AA-1-LG2                  
                  2  AF    1           1 J5D003BY-1-L1                    65
                           2             PACKET SWITCH UNIT
                           3             MODEL 2
                           4 C           SM 001 SMC 000/PSU 02/EQL 00053
                           5             FUSE POS 050A,050B,050C
                           6             FUSE POS 159A,159B,159C
                           7             E/W
                  2  AG    1           2 J5D003BY-1-L14C                 
                  2  AH    1           2 J5D003BY-1-L15                  
                  2  AJ    1           4 J5D003BY-1-L18A                 
                           2 C           SM 001 SMC 000/EQL 00053-014,
                           3 #           00053-046,00053-128,00053-144
                  2  AK    1           2 J5D003BY-1-L24                  
                  2  AL    1           5 J5D003BY-1-L25                  
                           2 C           SM 001 SMC 000/EQL 00053-006,
                           3 #           00053-022,00053-054,00053-136,
                           4 #           00053-168
                  2  AM    1           4 J5D003BY-1-L30B                 
                           2 C           SM 001 SMC 000/EQL 00053-062,
                           3 #           00053-176,00053-030,00053-160
                  2  AN    1           1 J5D003BY-1-L41                  
                           2 C           SM 001 SMC 000/EQL 00053-152
                  2  AP    1           7 J5D003BY-1-L65                  
0                          2 C           SM 001 SMC 000/EQL 00053-006,
                           3 #           00053-022,00053-030,00053-054,
                           4 #           00053-136,00053-160,00053-168
                  2  AQ    1           1 J5D003BY-1-L66                  
                           2 C           SM 001 SMC 000/EQL 00053-038
                  2  AR    1           1 J5D003BY-1-L102                 
                  2  AS    1           1 J5D003BY-1-L106                 
                  2  AT    1           1 J5D003BY-1-L108                 
                  2  AU    1           2 J5D003BY-1-L110                 
                  2  AV    1           2 J5D003BY-1-LD1                  
                  2  AW    1           1 J5D003BY-1-LD3                  
                  2  AX    1           1 J5D003BY-1-LE4                  
                  2  AY    1           1 J5D003BY-1-LF4                  
                  2  BA    1           1 J5D003BY-1-LF5                  
                  2  BB    1           1 J5D003BY-1-LG1                  
                  2  BC    1           1 J5D003FN-1-L500                  27
                           2             DIGITAL LINE TRUNK UNIT
                           3             MODEL 3
                           4 C           SM 001 SMC 000/DLTU 0 /EQL 00062
                           5             FUSE POS 059A&059B&059C&059D
                           6             FUSE POS 168A&168B&168C
                           7             E/W
                  2  BD    1           2 J5D003FN-1-L6A                  
                           2 C           SM 001 SMC 000/EQL 00062-030,
                           3 #           00062-038
                  2  BE    1           2 J5D003FN-1-L7A                  
                           2 C           SM 001 SMC 000/EQL 00062-014,
                           3 #           00062-022
                  2  BF    1           1 J5D003FN-1-L3                   
                  2  BG    1           1 J5D003FN-1-LF5                  
                  2  BH    1           1 J5D003FN-1-LF6                  
                  2  BJ    1           1 J5D003FN-1-LF                   
                  2  BK    1           1 J5D003FN-1-LG2                  
                  2  BL    1           1 J5D003FJ-1-L200                  84
                           2             MODULAR FUSE/FILTER UNIT
                           3 C           SM 001 SMC 000/EQL 00069
                           4             E/W
                  2  BM    1           1 J5D003FJ-1-LCK                  
                  2  BN    1           1 J5D003NK-1-L1                    17
                           2             SWITCHING MODULE PROCESSOR
                           3             MODEL 6
                           4 C           SM 001 SMC 000/SMU6/EQL 00015
                           5             FUSE POS 014A,014B,014C,023A
                           6             FUSE POS 118A,118B,118C,127A
                           7             E/W
                  2  BP    1           2 J5D003NK-1-L2A                  
                  2  BQ    1           2 J5D003NK-1-L3                   
                  2  BR    1           2 J5D003NK-1-L4                   
                  2  BS    1           2 J5D003NK-1-L5                   
                           2 C           SM 001 SMC 000/EQL 00011-070,
                           3             00019-070
                  2  BT    1           2 J5D003NK-1-L6                   
                  2  BU    1           2 J5D003NK-1-L7                   
0                 2  BV    1           2 J5D003NK-1-L8                   
                  2  BW    1           2 J5D003NK-1-L9                   
                  2  BX    1           2 J5D003NK-1-L10                  
                  2  BY    1           4 J5D003NK-1-L11A                 
                           2 C           SM 001 SMC 000/EQL 00015-008,
                           3             00015-016,00015-039,00015-047
                  2  CA    1           2 J5D003NK-1-L12                  
                  2  CB    1           2 J5D003NK-1-L14                  
                  2  CC    1           2 J5D003NK-1-L15                  
                  2  CD    1           3 J5D003NK-1-L16                  
                           2 C           SM 001 SMC 000/EQL 00011-156,
                           3             00019-156,00011-166
                  2  CE    1          31 J5D003NK-1-L18                  
                           2 C           SM 001 SMC 000/EQL
                           3             00015-000-120 (NLI),
                           4             00015-000-110 (NLI),
                           5             00015-008-120 (NLI),
                           6             00015-008-110 (NLI),
                           7             00015-008-077 (NLI),
                           8             00015-008-067 (NLI),
                           9             00015-008-056 (PLI),
                          10             00015-008-046 (PLI),
                          11             00015-008-036 (NLI),
                          12             00015-008-023 (NLI),
                          13             00015-008-013 (PLI),
                          14             00015-008-003 (PLI),
                          15             00015-016-120 (NLI),
                          16             00015-016-110 (NLI),
                          17             00015-016-100 (PLI),
                          18             00015-016-087 (PLI),
                          19             00015-032-120 (NLI),
                          20             00015-032-110 (NLI),
                          21             00015-039-120 (NLI),
                          22             00015-039-110 (NLI),
                          23             00015-039-077 (NLI),
                          24             00015-039-067 (NLI),
                          25             00015-039-056 (PLI),
                          26             00015-039-046 (PLI),
                          27             00015-039-036 (NLI),
                          28             00015-039-023 (NLI),
                          29             00015-039-013 (PLI),
                          30             00015-039-003 (PLI),
                          31             00015-047-120 (NLI),
                          32             00015-047-110 (NLI),
                          33             00015-047-100 (PLI)
                  2  CF    1           2 J5D003NK-1-L19                  
                           2 C           SM 001 SMC 000/EQL
                           3             00015-008-100 (PLI),
                           4             00015-039-100 (PLI)
                  2  CG    1           4 J5D003NK-1-L20                  
                  2  CH    1           1 J5D003NK-1-L23                  
                           2 C           SM 001 SMC 000/EQL 00019-166
                  2  CJ    1           1 J5D003NK-1-L24                  
0                          2 C           SM 001 SMC 000/EQL 00019-166
                  2  CK    1           2 J5D003NK-1-LB1                  
                           2             KLX APPARATUS BLANK
                           3 C           SM 001 SMC 000/EQL 00015-024,
                           4             00015-055
                  2  CL    1           4 J5D003NK-1-LB2                  
                           2             171D TYPE APPARATUS BLANK
                           3 C           SM 001 SMC 000/EQL 00015-078,
                           4             00015-078,00015-086,00015-086
                  2  CM    1           2 J5D003NK-1-LB3                  
                           2             171E TYPE APPARATUS BLANK
                           3 C           SM 001 SMC 000/EQL 00011-176,
                           4             00019-176
                  2  CN    1           6 J5D003NK-1-LB4                  
                           2             BKXL TRIPLE POSITION APP. BLANK
                           3 C           SM 001 SMC 000
                           4             EQL 00015-016-046,00015-024-110,
                           5             00015-024-046,00015-047-046,
                           6             00015-055-110,00015-055-046
                  2  CP    1          25 J5D003NK-1-LB5                  
                           2             BKXL SINGLE POSITION APP. BLANK
                           3 C           SM 001 SMC 000
                           4             EQL 00015-008-087,00015-016-077,
                           5             00015-016-067,00015-016-023,
                           6             00015-016-013,00015-016-003,
                           7             00015-024-087,00015-024-077,
                           8             00015-024-067,00015-024-023,
                           9             00015-024-013,00015-024-003,
                          10             00015-039-087,00015-047-087,
                          11             00015-047-077,00015-047-067,
                          12             00015-047-023,00015-047-013,
                          13             00015-047-003,00015-055-087,
                          14             00015-055-077,00015-055-067,
                          15             00015-055-023,00015-055-013,
                          16             00015-055-003
                  2  CQ    1           1 J5D003NK-1-LD1                  
                  2  CR    1           1 J5D003NK-1-LF1                  
                  2  CS    1           1 J5D003NK-1-LK18                 
                  2  CT    1 52C       1 ED5D693-15-G2EVN                 53
                           2             INTRA-CABINET CA ASSY -EVEN-
                           3 C           SM 001 SMC 000
                           4             E/W
                  2  CU    1           1 ED5D693-15-G896C                
                           2             IPS-H 00/EQL 00037
                           3             FUSE 032A/10A/CP 04,05,08
                           4             FUSE 032B/10A/CP 12,13,16,17
                           5             FUSE 032C/10A/CP 01,09
                  2  CV    1           1 ED5D693-15-G896D                
                           2             iOIU 00/EQL 00037
                           3             FUSE 041A/10A/SLOT 03,06,07,10
                           4             FUSE 041B/10A/SLOT 12,13,16,17
                           5             FUSE 041C/10A/
                  2  CW    1           1 ED5D693-15-G914                 
0                          2             PSU2 02/EQL 00053
                           3             FUSE 050A/10A/CP 006-030
                           4             FUSE 050B/10A/CP 038-062
                           5             FUSE 050C/10A/CP 070-088
                  2  CX    1           1 ED5D693-15-G580                 
                           2             DLTU3 00/EQL 00062
                           3             FUSE 059A/5A/CP 006,014,046,082
                           4             FUSE 059B/5A/CP 114,142,166
                           5             FUSE 059C/5A/CP 030,066,098
                           6             FUSE 059D/5A/CP 130,158
                  2  CY    1 52C       1 ED5D693-15-G1ODD                 53
                           2             INTRA-CABINET CA ASSY -ODD-
                           3 C           SM 001 SMC 000
                           4             E/W
                  2  DA    1           1 ED5D693-15-G897C                
                           2             IPS-H 00/EQL 00037
                           3             FUSE 141A/10A/CP 10,18
                           4             FUSE 141B/10A/CP 11,14,15
                           5             FUSE 141C/10A/CP 02,03,06,07
                  2  DB    1           1 ED5D693-15-G897D                
                           2             iOIU 00/EQL 00037
                           3             FUSE 150A/10A/
                           4             FUSE 150B/10A/CP 11,14,15,18
                           5             FUSE 150C/10A/CP 04,05,08,09
                  2  DC    1           1 ED5D693-15-G915                 
                           2             PSU2 02/EQL 00053
                           3             FUSE 159A/10A/CP 100-120
                           4             FUSE 159B/10A/CP 128-152
                           5             FUSE 159C/10A/CP 160-184
                  2  DD    1           1 ED5D693-15-G581                 
                           2             DLTU3 00/EQL 00062
                           3             FUSE 168A/5A/CP 122,150,174
                           4             FUSE 168B/5A/CP 006,022,058,090
                           5             FUSE 168C/5A/CP 038,074,106
                  2  DE    1           1 ED5D693-15-G898B                 53
                           2             INTRA-CABINET CA ASSY
                           3             FAN/EQL 00026F
                           4             FUSE 032D/3A/
                           5             FUSE 141D/3A/
                  2  DF    1           1 ED5D693-15-G898C                 53
                           2             INTRA-CABINET CA ASSY
                           3             FAN/EQL 00046F
                           4             FUSE 050D/3A/
                           5             FUSE 159D/3A/
                  2  DG    1           1 ED5D693-15-G899B                 53
                           2             INTRA-CABINET CA ASSY
                           3             FAN/EQL 00026R
                           4             FUSE 041D/3A/
                           5             FUSE 150D/3A/
                  2  DH    1           1 ED5D693-15-G899C                 53
                           2             INTRA-CABINET CA ASSY
                           3             FAN/EQL 00046R
                           4             FUSE 023D/3A/
0                          5             FUSE 127D/3A/
                  2  DJ    1           4 ED5D734-14-G164                  47
                           2             FAN AND FUSE ALARM CABLE
                           3 C           SM 001 SMC 000
                  2  DK    1           1 ED5D734-14-G165                  47
                           2             FAN AND FUSE ALARM CABLE
                           3 C           SM 001 SMC 000
                  2  DL    1           2 ED5D734-14-G200                  47
                           2             FUSE FILTER ALM MULT CABLES
                           3             SHOP INFORMATION
                           4             SM    EQL    TERM   EQL    TERM
                           5 SP          001 00068-089-103
                           6 SP          001 00068-089-106
                  2  DM    1           3 ED5D867-16-G6                     5
                           2             FAN AND FUSE ALARM CABLE
                           3 C           SM 001 SMC 000
                  2  DN    1           1 ED5D734-13-G16                    8
                           2             SHOP INFORMATION
                           3             PB  SM FROM EQL TERM  TO EQL  TERM
                           4 SP          1  001 00037-175-113 00019-138-145
                           5                     IPS  00,SG 1
                  2  DP    1           1 ED5D734-13-G18                    8
                           2             SHOP INFORMATION
                           3             PB  SM FROM EQL TERM  TO EQL  TERM
                           4 SP          1  001 00037-016-113 00019-138-132
                           5                     IPS  00,SG 0
                  2  DQ    1           1 ED5D734-13-G20                    8
                           2             SHOP INFORMATION
                           3             PB  SM FROM EQL TERM  TO EQL  TERM
                           4 SP          0  001 00037-175-100 00011-138-145
                           5                     IPS  00,SG 1
                  2  DR    1           1 ED5D734-13-G22                    8
                           2             SHOP INFORMATION
                           3             PB  SM FROM EQL TERM  TO EQL  TERM
                           4 SP          0  001 00037-016-100 00011-138-132
                           5                     IPS  00,SG 0
                  2  DS    1           5 ED5D734-25-G13                   14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           0 001 00011-146-117  00019-156-445
                           6                     BUS 00,PORT 04 DSC,SG1/0
                           7 SP           0 001 00011-146-121  00019-156-440
                           8                     BUS 00,PORT 05 DSC,SG1/1
                           9 SP           0 001 00011-146-132  00019-156-436
                          10                     BUS 00,PORT 06 DSC,SG1/2
                          11 SP           0 001 00011-146-136  00019-156-432
                          12                     BUS 00,PORT 07 DSC,SG1/3
                          13 SP           0 001 00011-146-300  00019-166-445
                          14                     BUS 00,PORT 12 DSC,SG1/0
                  2  DT    1           2 ED5D734-25-G14                   14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
0                          4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           1 001 00019-146-149  00011-166-236
                           6                     BUS 10,PORT 10 DSC,SG0/2
                           7 SP           1 001 00019-146-153  00011-166-232
                           8                     BUS 10,PORT 11 DSC,SG0/3
                  2  DU    1           2 ED5D734-25-G15                   14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           1 001 00019-146-140  00011-166-245
                           6                     BUS 10,PORT 08 DSC,SG0/0
                           7 SP           1 001 00019-146-145  00011-166-240
                           8                     BUS 10,PORT 09 DSC,SG0/1
                  2  DV    1           4 ED5D734-25-G16                   14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           1 001 00019-146-100  00011-156-245
                           6                     BUS 10,PORT 00 DSC,SG0/0
                           7 SP           1 001 00019-146-104  00011-156-240
                           8                     BUS 10,PORT 01 DSC,SG0/1
                           9 SP           1 001 00019-146-108  00011-156-236
                          10                     BUS 10,PORT 02 DSC,SG0/2
                          11 SP           1 001 00019-146-113  00011-156-232
                          12                     BUS 10,PORT 03 DSC,SG0/3
                  2  DW    1           1 ED5D734-25-G19                   14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           1 001 00019-146-313 F00037-185-113
                           6                     BUS 10,PORT 15  IPS 00
                  2  DX    1           2 ED5D734-25-G22                   14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           0 001 00011-146-313 F00037-185-100
                           6                     BUS 00,PORT 15  IPS 00
                           7 SP           1 001 00019-146-308 F00037-006-113
                           8                     BUS 10,PORT 14  IPS 00
                  2  DY    1           1 ED5D734-25-G24                   14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           0 001 00011-146-308 F00037-006-100
                           6                     BUS 00,PORT 14  IPS 00
                  2  EA    1           4 ED5D734-25-G3                    14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           0 001 00011-146-100  00011-156-445
                           6                     BUS 00,PORT 00 DSC,SG0/0
                           7 SP           0 001 00011-146-104  00011-156-440
                           8                     BUS 00,PORT 01 DSC,SG0/1
0                          9 SP           0 001 00011-146-108  00011-156-436
                          10                     BUS 00,PORT 02 DSC,SG0/2
                          11 SP           0 001 00011-146-113  00011-156-432
                          12                     BUS 00,PORT 03 DSC,SG0/3
                  2  EB    1           7 ED5D734-25-G4                    14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           1 001 00019-146-117  00019-156-245
                           6                     BUS 10,PORT 04 DSC,SG1/0
                           7 SP           1 001 00019-146-132  00019-156-236
                           8                     BUS 10,PORT 06 DSC,SG1/2
                           9 SP           1 001 00019-146-136  00019-156-232
                          10                     BUS 10,PORT 07 DSC,SG1/3
                          11 SP           0 001 00011-146-140  00011-166-445
                          12                     BUS 00,PORT 08 DSC,SG0/0
                          13 SP           0 001 00011-146-145  00011-166-440
                          14                     BUS 00,PORT 09 DSC,SG0/1
                          15 SP           0 001 00011-146-149  00011-166-436
                          16                     BUS 00,PORT 10 DSC,SG0/2
                          17 SP           0 001 00011-146-153  00011-166-432
                          18                     BUS 00,PORT 11 DSC,SG0/3
                  2  EC    1           1 ED5D734-25-G5                    14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           1 001 00019-146-121  00019-156-240
                           6                     BUS 10,PORT 05 DSC,SG1/1
                  2  ED    1           1 ED5D734-25-G6                    14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           1 001 00019-146-300  00019-166-245
                           6                     BUS 10,PORT 12 DSC,SG1/0
                  2  EE    1           6 ED5D734-25-G29                   14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           1 001 00019-146-332  00062-022-308
                           6                     BUS 10,PORT 18 DLTU 00DFI2
                           7 SP           1 001 00019-146-336  00062-022-108
                           8                     BUS 10,PORT 19 DLTU 00DFI2
                           9 SP           1 001 00019-146-340  00062-030-308
                          10                     BUS 10,PORT 20 DLTU 00DFI3
                          11 SP           1 001 00019-146-345  00062-030-108
                          12                     BUS 10,PORT 21 DLTU 00DFI3
                          13 SP           1 001 00019-146-349  00062-038-308
                          14                     BUS 10,PORT 22 DLTU 00DFI4
                          15 SP           1 001 00019-146-353  00062-038-108
                          16                     BUS 10,PORT 23 DLTU 00DFI4
                  2  EF    1           2 ED5D734-25-G30                   14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
0                          4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           1 001 00019-146-317  00062-014-308
                           6                     BUS 10,PORT 16 DLTU 00DFI1
                           7 SP           1 001 00019-146-321  00062-014-108
                           8                     BUS 10,PORT 17 DLTU 00DFI1
                  2  EG    1           8 ED5D734-25-G33                   14
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PIDB SM    EQL  TERM      EQL  TERM
                           5 SP           0 001 00011-146-317  00062-014-304
                           6                     BUS 00,PORT 16 DLTU 00DFI1
                           7 SP           0 001 00011-146-321  00062-014-104
                           8                     BUS 00,PORT 17 DLTU 00DFI1
                           9 SP           0 001 00011-146-332  00062-022-304
                          10                     BUS 00,PORT 18 DLTU 00DFI2
                          11 SP           0 001 00011-146-336  00062-022-104
                          12                     BUS 00,PORT 19 DLTU 00DFI2
                          13 SP           0 001 00011-146-340  00062-030-304
                          14                     BUS 00,PORT 20 DLTU 00DFI3
                          15 SP           0 001 00011-146-345  00062-030-104
                          16                     BUS 00,PORT 21 DLTU 00DFI3
                          17 SP           0 001 00011-146-349  00062-038-304
                          18                     BUS 00,PORT 22 DLTU 00DFI4
                          19 SP           0 001 00011-146-353  00062-038-104
                          20                     BUS 00,PORT 23 DLTU 00DFI4
                  2  EH    1           1 ED5D734-26-G13                   15
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PICB SM    EQL  TERM     EQL  TERM
                           5 SP           0 001 00011-130-132  00019-166-451
                           6                     BUS 00,PORT 3   DSC,SG1
                  2  EJ    1           1 ED5D734-26-G14                   15
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PICB SM    EQL  TERM     EQL  TERM
                           5 SP           0 001 00011-130-145  00019-156-451
                           6                     BUS 00,PORT 1   DSC,SG1
                  2  EK    1           2 ED5D734-26-G15                   15
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PICB SM    EQL  TERM     EQL  TERM
                           5 SP           1 001 00019-130-151  00011-156-251
                           6                     BUS 10,PORT 0   DSC,SG0
                           7 SP           1 001 00019-130-138  00011-166-251
                           8                     BUS 10,PORT 2   DSC,SG0
                  2  EL    1           1 ED5D734-26-G20                   15
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PICB SM    EQL  TERM     EQL  TERM
                           5 SP           1 001 00019-130-113 F00037-180-106
                           6                     BUS 10,PORT 5   IPS 00
                  2  EM    1           1 ED5D734-26-G21                   15
                           2             INTRA-MODULE CA ASSY
0                          3             SHOP INFORMATION
                           4             PICB SM    EQL  TERM     EQL  TERM
                           5 SP           1 001 00019-130-119 F00037-011-106
                           6                     BUS 10,PORT 4   IPS 00
                  2  EN    1           1 ED5D734-26-G22                   15
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PICB SM    EQL  TERM     EQL  TERM
                           5 SP           0 001 00011-130-113 F00037-180-100
                           6                     BUS 00,PORT 5   IPS 00
                  2  EP    1           1 ED5D734-26-G24                   15
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PICB SM    EQL  TERM     EQL  TERM
                           5 SP           0 001 00011-130-119 F00037-011-100
                           6                     BUS 00,PORT 4   IPS 00
                  2  EQ    1           1 ED5D734-26-G3                    15
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PICB SM    EQL  TERM     EQL  TERM
                           5 SP           1 001 00019-130-145  00019-156-251
                           6                     BUS 10,PORT 1   DSC,SG1
                  2  ER    1           3 ED5D734-26-G4                    15
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PICB SM    EQL  TERM     EQL  TERM
                           5 SP           0 001 00011-130-151  00011-156-451
                           6                     BUS 00,PORT 0   DSC,SG0
                           7 SP           0 001 00011-130-138  00011-166-451
                           8                     BUS 00,PORT 2   DSC,SG0
                           9 SP           1 001 00019-130-132  00019-166-251
                          10                     BUS 10,PORT 3   DSC,SG1
                  2  ES    1           2 ED5D734-26-G29                   15
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PICB SM    EQL  TERM     EQL  TERM
                           5 SP           1 001 00019-130-351  00062-030-113
                           6                     BUS 10,PORT 8  DLTU 00DFI3
                           7 SP           1 001 00019-130-345  00062-038-113
                           8                     BUS 10,PORT 9  DLTU 00DFI4
                  2  ET    1           2 ED5D734-26-G31                   15
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PICB SM    EQL  TERM     EQL  TERM
                           5 SP           1 001 00019-130-106  00062-014-113
                           6                     BUS 10,PORT 6  DLTU 00DFI1
                           7 SP           1 001 00019-130-100  00062-022-113
                           8                     BUS 10,PORT 7  DLTU 00DFI2
                  2  EU    1           3 ED5D734-26-G33                   15
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PICB SM    EQL  TERM     EQL  TERM
                           5 SP           0 001 00011-130-106  00062-014-313
0                          6                     BUS 00,PORT 6  DLTU 00DFI1
                           7 SP           0 001 00011-130-100  00062-022-313
                           8                     BUS 00,PORT 7  DLTU 00DFI2
                           9 SP           0 001 00011-130-345  00062-038-313
                          10                     BUS 00,PORT 9  DLTU 00DFI4
                  2  EV    1           1 ED5D734-26-G34                   15
                           2             INTRA-MODULE CA ASSY
                           3             SHOP INFORMATION
                           4             PICB SM    EQL  TERM     EQL  TERM
                           5 SP           0 001 00011-130-351  00062-030-313
                           6                     BUS 00,PORT 8  DLTU 00DFI3
                  2  EW    1          10 ED5D872-30-G328                  30
                           2             INTRA-MODULE CA ASSY
                           3             PCT   SHOP INFORMATION
                           4             T/R SM    EQL    TERM   EQL    TERM
                           5 SP           0 001 00037-003-000 00015-008-056
                           6                   iOIU-00 SG-0   SMU6 02,PORT 2
                           7 SP           1 001 00037-004-000 00015-039-056
                           8                   iOIU-00 SG-0   SMU6 12,PORT 2
                           9 SP           0 001 00037-003-001 00015-008-046
                          10                   iOIU-00 SG-0   SMU6 02,PORT 3
                          11 SP           1 001 00037-004-001 00015-039-046
                          12                   iOIU-00 SG-0   SMU6 12,PORT 3
                          13 SP           0 001 00037-003-002 00015-008-013
                          14                   iOIU-00 SG-0   SMU6 03,PORT 2
                          15 SP           1 001 00037-004-002 00015-039-013
                          16                   iOIU-00 SG-0   SMU6 13,PORT 2
                          17 SP           0 001 00037-005-000 00015-008-003
                          18                   iOIU-00 SG-0   SMU6 03,PORT 3
                          19 SP           1 001 00037-006-000 00015-039-003
                          20                   iOIU-00 SG-0   SMU6 13,PORT 3
                          21 SP           0 001 00037-005-001 00015-016-100
                          22                   iOIU-00 SG-0   SMU6 04,PORT 2
                          23 SP           1 001 00037-006-001 00015-047-100
                          24                   iOIU-00 SG-0   SMU6 14,PORT 2
                  2  EX    1           1 ED5D872-30-G728                  30
                           2             INTRA-MODULE CA ASSY
                           3             PCT   SHOP INFORMATION
                           4             T/R SM    EQL    TERM   EQL    TERM
                           5 SP           0 001 00015-008-100 00053-088-132
                           6                    SMU6 01,PORT 2 PSU-0 SG-0
                  2  EY    1           1 ED5D872-30-G733                  30
                           2             INTRA-MODULE CA ASSY
                           3             PCT   SHOP INFORMATION
                           4             T/R SM    EQL    TERM   EQL    TERM
                           5 SP           1 001 00015-039-100 00053-100-132
                           6                    SMU6 11,PORT 2 PSU-0 SG-1
                  2  FA    1           1 ED5D785-70-G2B                   24
                           2             BLUE EMC DOORS FOR SMC
                  2  FB    1           2 ED5D785-70-G3B                   24
                           2             BLUE EMC DOORS FOR SMC
                  2  FC    1           1 ED5D785-70-G4A                   24
                           2             BLUE EMC DOORS FOR SMC
0                 3        1 SPR       1 J5D003NK-1-L18                   17
                           2 SCE         QD/QD/X
                           3             BKXL1 MTRJ CP
0                 4        1          20 408824332
                           2 SCE         QD/QD/X
                           3             L9 CONNECTOR
