LES015E
006
0                 1        1           5 300615994
                           2 SCE         QD/QD/X
                           3             cdma certifcation lable for
                           4             dcs, ecp, ims (1 per cabinet)
0                 2        1           4 ED5D779-70-G1B                    9
                           2 SCE         QD/QD/X
                           3             lineup cbrk 2'6" to supt ph ii/fac ca
0                 3        1           1 ED5D779-70-G1D                    9
                           2 SCE         QD/QD/X
                           3             lineup cbrk 2'6" to supt LPDC cabinet
0                 4        1           5 ED5D779-70-G2                     9
                           2 SCE         QD/QD/X
                           3             cover panel required one per G-1B
0                 5        1           2 ED5D779-70-G3G                    9
                           2 SCE         QD/QD/X
                           3             coupling plate required per junction 
                           4             inst cab under both side of junctiob
0                 6        1           6 ED5D786-70-G1B                   21
                           2 SCE         QD/QD/X
                           3             end guard right/left side  
0                 7        1           2 ED5D518-10-G3                    15
                           2 SCE         QD/QD/X
                           3             a pair of single storage spool (metal
                           4             (x3 two for each smc or cm2 pair)
0                 8        1           4 900666256         
                           2 SCE         QD/QD/X
                           3             toplock flange nut used for 5ess cab 
0                 9        1           4 814251914                            
                           2 SCE         QD/QD/X
                           3             washer for 1/2" screw   
0                10        1           4 843084385                  
                           2 SCE         QD/QD/X
0                          3             1/2-13 x 5 3/4 hhc screw
0                11        1           4 843082470  
                           2 SCE         QD/QD/X
                           3             spacer used between 5ess cab
0                12        1           5 300616232
                           2 SCE         QD/QD/X
                           3             pedestal pair, 325mm hei for space: 2
0                13        1           5 300616448
                           2 SCE         QD/QD/X
                           3             hdwr kit for one cab space raising ba
0                14        1           5 108175514
                           2 SCE         QD/QD/X
                           3             fasten a global cab on rasing base
0                15        1         320 408825263         FT
                           2 SCE         QD/QD/X
                           3             KS24194 L-11, 350KCMIL STRD WIRE, GY
                           4             2 RUNS 80  FT LG,  -48V  > LPDC00-01
                           5             2 RUNS 80  FT LG,  0V  > LPDC00
0                16        1          26 405348277
                           2 SCE         QD/QD/X
                           3             WP91412 L-61, TWO HOLE CONNR (350MCM 
0                17        1          10 801472846
                           2 SCE         QD/QD/X
                           3             (3/8-16 X 1 1/4 CAP SCREW) SCREW M10 
0                18        1          10 814251898
                           2 SCE         QD/QD/X
                           3             3/8 WASHER
0                19        1          10 804236388
                           2 SCE         QD/QD/X
                           3             3/8 LOCK WASHER
0                20        1          10 841064777
                           2 SCE         QD/QD/X
                           3             (3/8-16 HEX NUT) HEX NUT M10
0                21        1          10 100393156                            
                           2 SCE         QD/QD/X
                           3             145C NO. PLATE FOR POW&GRD LEAD ID   
0                22        1          10 996346862         FT                 
                           2 SCE         QD/QD/X
                           3             #6 AWG BARE TINNED WIRE FOR LINEUP CA
0                23        1         100 408826832         FT       
                           2 SCE         QD/QD/X
                           3             1/0 AWG STRD WIRE, G/Y   
                           4             2 RUN FOR LPDC TO 5EFGB      
0                24        1         100 408826881         FT    
                           2 SCE         QD/QD/X
                           3             6 AWG STRD WIRE, G/Y    
0                25        1           4 ED4C686-70-G18A                   8
                           2 SCE         QD/QD/X
                           3             GROUNDING KIT 914MM LONG, #6 AWG STRA
0                          4             BARE COPPER WIRE. 1 2-HOLE LUG AT ONE
                           5             FOR USE IN 6-FT CAB MODEL 5E-2000 PH 
0                26        1           5 405348228                            
                           2 SCE         QD/QD/X
                           3             WP91412 L-56, CONNR (1/0 / 3/8)
0                27        1          10 801472846                            
                           2 SCE         QD/QD/X
                           3             (3/8-16 X 1 1/4 CAP SCREW),SCREW M10 
0                28        1          10 814251898
                           2 SCE         QD/QD/X
                           3             3/8 WASHER 
0                29        1          10 804236388                           
                           2 SCE         QD/QD/X
                           3             3/8 LOCK WASHER
0                30        1          10 841064777                     
                           2 SCE         QD/QD/X
                           3             (3/8-16 HEX NUT) HEX NUT M10   
0                31        1           4 ED4C686-70-G12                    8
                           2 SCE         QD/QD/X
                           3             HDWR TO CONNECT A #6 AWG LUG TO BUS B
0                32        1           4 ED4C686-70-G13                    8
                           2 SCE         QD/QD/X
                           3             2-HOLE LUG TERMINAL FOR #6 AWG CONDUC
0                33        1           6 ED4C686-70-G19                    8
                           2 SCE         QD/QD/X
                           3             "C" TAP TO CONNECT TWO #6 AWG GROUND 
                           4             WHERE NO INSULATION IS NECESSARY.
0                34        1           1 ED4C471-30-G21                    9
                           2 SCE         QD/QD/X
                           3             SPLICE PLATE MOUNTING ON 20" LADDER C
0                35        1           2 804002988        
                           2 SCE         QD/QD/X
                           3             CEILING SUPT
0                36        1           2 406922880                
                           2 SCE         QD/QD/X
                           3             5/8-11 X 1 1/4" THREADED ROD
0                37        1           2 841063670            
                           2 SCE         QD/QD/X
                           3             (5/8"-11 HEX NUT) HEX NUT M16
0                38        1           4 841209729          
                           2 SCE         QD/QD/X
                           3             3/8-16 X 2 SELF DRILL ANCHOR    
0                39        1           1 804117190
                           2 SCE         QD/QD/X
                           3             "DO NOT DISCONNECT" TAG 
0                40        1           2 995831013
                           2 SCE         QD/QD/X
                           3             GRAY SHEET FIBER   
0                41        1           1 997104575        
                           2 SCE         QD/QD/X
                           3             INSULATED THREADLESS CONN FOR 3/4 CND
0                42        1           1 995230844        
                           2 SCE         QD/QD/X
                           3             OPEN BUSHING FOR END OF 3/4 RIGID CND
0                43        1           1 841059926        
                           2 SCE         QD/QD/X
                           3             1/4-20 X 1 1/2 PHM SCREW 
0                44        1           4 406171439        
                           2 SCE         QD/QD/X
                           3             DROP IN ANCHOR FOR 1/4" SCREW OR BOLT
0                45        1           4 801725789
                           2 SCE         QD/QD/X
                           3             WASHER
0                46        1           2 403854482       
                           2 SCE         QD/QD/X
                           3             10 FT 1100 SERIES RACEWAY BASE
0                47        1           4 403854367                           
                           2 SCE         QD/QD/X
                           3             5 FT 1100 SERIES RACEWAY COVER
0                48        1           8 H555-120-G12                     23
                           2 SCE         QD/QD/X
                           3             1/4-20 X 5/8 FHM SCR 
0                49        1          36 ED5D832-70-G12                    8
                           2 SCE         QD/QD/X
                           3             POWER LINE FILTER
